module.exports = {
    AudioVideo: require('./audioVideo'),
    Info: require('./commands/info'),
    SetTie: require('./commands/set-tie'),
    GetTie: require('./commands/get-tie'),
    Untie: require('./commands/untie'),
    SetGain: require('./commands/set-gain'),
    GetGain: require('./commands/get-gain'),
    SetVol: require('./commands/set-vol'),
    GetVol: require('./commands/get-vol'),
    Mute: require('./commands/mute'),
    Unmute: require('./commands/unmute'),
    IsMuted: require('./commands/is-muted'),
    SavePreset: require('./commands/save-preset'),
    RecallPreset: require('./commands/recall-preset'),
    ClearPreset: require('./commands/clear-preset'),
    ResetPresets: require('./commands/reset-presets'),
    ResetAudioLevels: require('./commands/reset-audio-levels'),
    ResetMutes: require('./commands/reset-mutes'),
    SystemReset: require('./commands/system-reset')
}
